import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "surface-tint": "#4059aa",
        "error-container": "#ffdad6",
        "background": "#faf8ff",
        "surface-container-low": "#f4f3fa",
        "inverse-primary": "#b6c4ff",
        "surface-container-highest": "#e3e1e9",
        "on-tertiary-fixed": "#341100",
        "secondary": "#00687a",
        "secondary-container": "#57dffe",
        "inverse-surface": "#2f3036",
        "primary-container": "#1e3a8a",
        "on-background": "#1a1b21",
        "secondary-fixed-dim": "#4cd7f6",
        "surface-dim": "#dad9e1",
        "primary-fixed": "#dce1ff",
        "tertiary-container": "#6e2c00",
        "on-tertiary": "#ffffff",
        "outline": "#757682",
        "surface-variant": "#e3e1e9",
        "inverse-on-surface": "#f1f0f7",
        "primary-fixed-dim": "#b6c4ff",
        "on-secondary-container": "#006172",
        "error": "#ba1a1a",
        "surface-container-high": "#e9e7ef",
        "tertiary": "#4b1c00",
        "surface-container": "#eeedf4",
        "secondary-fixed": "#acedff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#00164e",
        "tertiary-fixed": "#ffdbcb",
        "on-primary-container": "#90a8ff",
        "on-primary": "#ffffff",
        "on-surface-variant": "#444651",
        "surface": "#faf8ff",
        "on-primary-fixed-variant": "#264191",
        "primary": "#00236f",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#001f26",
        "on-surface": "#1a1b21",
        "on-tertiary-container": "#f39461",
        "on-secondary-fixed-variant": "#004e5c",
        "on-secondary": "#ffffff",
        "outline-variant": "#c5c5d3",
        "on-tertiary-fixed-variant": "#773205",
        "surface-bright": "#faf8ff",
        "tertiary-fixed-dim": "#ffb691",
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}

export default config
